version: "3.9"

services:

  web:
    build: .
    command: >
       sh -c 'python pytest
              python manage.py migrate &&
              python manage.py loaddata datadump.json &&
              python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"